### ISSUE TITLE
Add async Module & Instance initiating methods to avoid Chrome error

### ISSUE THREAD

**Issue by zimond** [kajacx/wasm-bridge#4]
Chrome up to v114 disallows wasm sync compilation on main thread unless they are less than 4KB. This may lead to wasm-bridge adopted application crash at runtime on Chrome. I think the JS api should still keep these async methods so users could decide if they need them or not.

**Comment by kajacx** [comment]
Hello, yea, I have ran into that too. The code is ready [here](https://github.com/kajacx/wasm-bridge/blob/master/crates/wasm-bridge-js/src/component/component.rs#L116), I will put it into a new version.

**Comment by zimond** [comment]
This code is for component, not for general wasm

**Comment by kajacx** [comment]
Oh, sorry. That should be relatively easy it to add, most work will be adding the automated test. I will get to it.

**Comment by kajacx** [comment]
@zimond Ok, added [`new_module_async`](https://github.com/kajacx/wasm-bridge/commits/master). Let me know if that works well or if you need `instantitate_async` too.

**Comment by zimond** [comment]
Yes it’s needed. The limitation is applied the whole process

**Comment by kajacx** [comment]
Thanks for the info, I will add it this afternoon.

**Comment by kajacx** [comment]
@zimond Ok, I added `instantitate_async` for use with the linker and `new_instance_async` as an option when you have no imports.

These are slightly different from `linker.instantitate_async` and `Instance::new_async` in that they do not require the `async` feature, since they do call synchronous methods on "sys" (non-wasm32 targets with wasmtime implementation).

That is kind of confusing, I will try to explain it in a table. But for now you should be able to make it work with the code in git. You can look at [this](instantitate_async) [test](https://github.com/kajacx/wasm-bridge/blob/master/tests/no_bindgen/imported_functions/host.rs#L61) for example usage.

**Comment by kajacx** [comment]
Ok, [here](https://github.com/kajacx/wasm-bridge/blob/master/docs/wasm_modules.md#sync-vs-async-methods) is the table with exaplanation.

**Comment by zimond** [comment]
please publish a new version with those new APIs, thanks
